# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f7315ae2b046892f04559c5795617fa91efbc8f02d4f3e664959cd2ea8a42cdd1ad8759be2cc112fdb9fa4153005a757e4593649fad5377d47d3ffda9f4025a

test:
  secret_key_base: ca571db4a03133760a56ebf8fb51a078c8b7e9bb3321ea170080a919231185a0dcbc506a7cc97221a5aaeb08518bb58e02987eec8f545ac193d7b39c74084a3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
